### ISSUE TITLE
Plastic multiplier part of the code is difficult to understood

### ISSUE THREAD

**Issue by Wang-bit385** [theysy/MML_SUBROUTINE_PUBLIC#1]
Hello, I am a graduate student from Yanshan University in Hebei, China.The role of KINEMATIC COMPONENT module subroutines is not understood in CPPM, noting that there is no description of pseudo-updating of state variables in the references

**Comment by theysy** [comment]
Hi,

The kinematic component is the partial derivative of the effective stress with respect to the effective plastic strain.
In other words, this is not critical if the effective stress is not influenced by the effective stress. (no state variables are involved in the model such as isotropic hardening)
This is obtained in deriving the consistency condition which is the material time derivative of the yield condition.
Due to the challenges of analytical derivation, alternatively, I simply used the numerical differentiation presuming the step size (corresponds to the effective plastic strain increment).

You may find further details from Yoon, S., & Barlat, F. (2023). Non-iterative stress projection method for anisotropic hardening. Mechanics of Materials, 183, 104683.

Cheers,
SY
________________________________
From: Wang-bit385 ***@***.***>
Sent: Wednesday, September 18, 2024 3:29 PM
To: theysy/mml_subroutine_public ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [theysy/mml_subroutine_public] Plastic multiplier part of the code is difficult to understood (Issue #1)


Hello, I am a graduate student from Yanshan University in Hebei, China.The role of KINEMATIC COMPONENT module subroutines is not understood in CPPM, noting that there is no description of pseudo-updating of state variables in the references

**Comment by Wang-bit385** [comment]
Thanks for your answer, i already understood the issue. Something other i want to consult you is that how to calibrate hill48 parameters according to your Matlab codes. In other words, I already have the stress-strain data，and what's the procedure for this work?

**Comment by theysy** [comment]
I am not quite sure how much you are familiar with anisotropic yield function.
Basically, you need to prepare r-values and normalized flow stresses for various angles from RD.
My code seeks for the optimal parameters of anisotropic yield function by matching the r-value and the normalized flow stress.
Stress-strain data is not necessary input for this optimization because the r-value is calculated using the derivative of yield function and the normalized flow stress is the ratio of 1st principal stress to the corresponding effective stress.
Surely, the r-value and normalized flow stress are obtained from stress-strain data.

**Comment by Wang-bit385** [comment]
Thanks for your answers. It is appreciated for answering my question in your busy time. 
(1)To the purpose of HILL48 identification, i For some reasons, i don't know  the r-values related to 0,45 and 90 degree. Only the stress-strain data, do you have any method obtain the r-values? 
(2)And the normalized flow stress, I normalized the yield stress, is that right? If not , do you have a reference about it? 
(3)I focus on the combination of QPE and  anyother Anisotropic elastoplasticity model, have you got any code related to QPE, the famous nonlinear elastic theory?

**Comment by theysy** [comment]
(1) You need to know e11 and e22 to get the R-values. The other way is to use Crystal plasticity if you have texture data of your material.
(2) Normalized flow stress means the flow stress normalized about the reference loading direction (which is usually RD) at the same plastic work level.
(3) I believe you are talking about the chord modulus model. Nope, the nonlinear elasticity is out of my interest. Instead, I implemented Yoshida-Uemori equation for chord modulus which is the much easier version of QPE. But, you may easily implement it by yourself as long as you understand the code. Indeed, it is easy to understand as I was told from my colleagues.

If you have any other questions about basic plasticity, refer to this book:
Mechanical Behavior of Materials - W. F. Hosford

**Comment by Wang-bit385** [comment]
Thank you for your careful reply. I have been trying to calibrate the hardening parameters of HAH11 with the MATLAB program you provided, but there are only one point in step1. Could you help me figure this out
[X80_HAH11.csv](https://github.com/user-attachments/files/17344446/X80_HAH11.csv)
<img width="240" alt="X80_HAH11" src="https://github.com/user-attachments/assets/276827ec-6a02-4cfb-a374-84ef6d1ac226">
<img width="398" alt="ONE_POINT" src="https://github.com/user-attachments/assets/cf7a8251-c007-45b0-9e2f-3d72fd71839c">
?
